permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Commit & push changes
        run: |
          git config --global user.name "Nabhansh Rishi Gaur"
          git config --global user.email "gamekillerr206@gmail.com"
          git add .
          git commit -m "Auto commit $(date)"
          git push
